#!/usr/bin/env bash

# Transfers a file from our client to a server

# Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Variables
file="$1"
ip="$2"
user="$3"
key="$4"

# Check if all parameters are provided
if [[ $# -ne 4 ]]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Check if file exists
if [[ ! -f $file ]]; then
    echo "Error: File $file not found"
    exit 1
fi

# Copy file to server
scp -o StrictHostKeyChecking=no -i "$key" "$file" "$user"@"$ip":~/ || exit 1
