#!/bin/bash

# Check if all required parameters are provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign variables to parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer the file to the server using scp
scp -i "$ssh_key_path" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/ 

# Check if the transfer was successful
if [ "$?" -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
fi

exit 0
