#!/usr/bin/env bash
# fix code listening on port 80

#navigate to sites-enabled folder for Nginx
cd /etc/nginx/sites_enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default;
service nginx restart
